server:
  port: 8888
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

ribbon:
  ReadTimeout: 5000  #openfeign 默认等待时长 1s
  ConnectTimeout: 5000
logging:
  level:
    com.yangtao.springcloud.service.PaymentFeignService: debug  #feign日志以什么样的级别监控什么接口

cloud-payment-service: #需要负载均衡的提供者名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #随机
