server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true

      filters: stat,wall
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC
      password: root
      username: root

      stat-view-servlet:  #druid 监控页功能
        enabled: true
        login-username: yangtao
        login-password: 123456
      web-stat-filter:  #druid 监控web功能
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'  #不监控
        url-pattern: /*   #监控所有请求
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka  #单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: payment8001 #修改eureka界面的主机名称
    prefer-ip-address: true #访问路径可以显示ip
    #lease-renewal-interval-in-seconds: 2  #Eureka客户端向服务端发送心跳的时间间隔
    #lease-expiration-duration-in-seconds: 10 #Eureka服务端在收到最后一次心跳后等待时间上限，超时将剔除





mybatis:
  mapper-locations: classpath*:mapper/*.xml