server:
  port: 6000
spring:
  application:
    name: gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

#显示路由zuul的端口配置，不配置无法访问 /routes
management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: ALWAYS

zuul:
  routes:
    cloud-payment-service: /provider/** #注意使用服务名
    cloud-order-service: /consumer/**  #注意使用服务名

  #prefix: /gateway                       #前缀
  ignored-services: '*'                  #禁用服务名访问(内网不受该限制)
  ignored-patterns: /**/cmap/**    #禁用某些路径
  sensitive-headers: '*'                 #解决走网关session变化